package eu.crg.ega.microservice.dto.message;

import com.fasterxml.jackson.annotation.JsonTypeInfo;

import eu.crg.ega.microservice.enums.MessageType;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.Builder;

/**
 * Represents a message generated by any service.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@Getter
@Setter
@Builder(builderMethodName = "messageBuilder")
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class ServiceMessage {

  private MessageHeader header;

  // Command or Event
  private MessageType messageType;
}
